// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

/**
 * OptionalNextjsBuildProps
 */
export interface OptionalNextjsBuildProps {
  /**
   * @stability stable
   */
  readonly streaming?: boolean;
  /**
   * @stability stable
   */
  readonly skipBuild?: boolean;
  /**
   * @stability stable
   */
  readonly quiet?: boolean;
  /**
   * @stability stable
   */
  readonly environment?: Record<string, string>;
  /**
   * @stability stable
   */
  readonly buildPath?: string;
  /**
   * @stability stable
   */
  readonly buildCommand?: string;
  /**
   * @stability stable
   */
  readonly nextjsPath?: string;
}
