// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { NextjsBuild, NextjsImageOverrides } from '../';
import type { aws_lambda, aws_s3 } from 'aws-cdk-lib';

/**
 * OptionalNextjsImageProps
 */
export interface OptionalNextjsImageProps {
  /**
   * Overrides.
   * @stability stable
   */
  readonly overrides?: NextjsImageOverrides;
  /**
   * Override function properties.
   * @stability stable
   */
  readonly lambdaOptions?: aws_lambda.FunctionOptions;
  /**
   * @stability stable
   */
  readonly nextBuild?: NextjsBuild;
  /**
   * The S3 bucket holding application images.
   * @stability stable
   */
  readonly bucket?: aws_s3.IBucket;
}
