// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { aws_route53, Duration } from 'aws-cdk-lib';

/**
 * OptionalARecordProps
 */
export interface OptionalARecordProps {
  /**
   * The target.
   * @stability stable
   */
  readonly target?: aws_route53.RecordTarget;
  /**
   * The resource record cache time to live (TTL).
   * @default Duration.minutes(30)
   * @stability stable
   */
  readonly ttl?: Duration;
  /**
   * The subdomain name for this record. This should be relative to the zone root name.
   * For example, if you want to create a record for acme.example.com, specify
   * "acme".
   *
   * You can also specify the fully qualified domain name which terminates with a
   * ".". For example, "acme.example.com.".
   * @default zone root
   * @stability stable
   */
  readonly recordName?: string;
  /**
   * The geographical origin for this record to return DNS records based on the user's location.
   * @stability stable
   */
  readonly geoLocation?: aws_route53.GeoLocation;
  /**
   * Whether to delete the same record set in the hosted zone if it already exists (dangerous!).
   * This allows to deploy a new record set while minimizing the downtime because the
   * new record set will be created immediately after the existing one is deleted. It
   * also avoids "manual" actions to delete existing record sets.
   *
   * > **N.B.:** this feature is dangerous, use with caution! It can only be used safely when
   * > `deleteExisting` is set to `true` as soon as the resource is added to the stack. Changing
   * > an existing Record Set's `deleteExisting` property from `false -> true` after deployment
   * > will delete the record!
   * @default false
   * @stability stable
   */
  readonly deleteExisting?: boolean;
  /**
   * A comment to add on the record.
   * @default no comment
   * @stability stable
   */
  readonly comment?: string;
  /**
   * The hosted zone in which to define the new record.
   * @stability stable
   */
  readonly zone?: aws_route53.IHostedZone;
}
