// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { aws_lambda } from 'aws-cdk-lib';
import type { NextjsBuild, NextjsRevalidationOverrides, NextjsServer } from '..';

/**
 * OptionalNextjsRevalidationProps
 */
export interface OptionalNextjsRevalidationProps {
  /**
   * Overrides.
   * @stability stable
   */
  readonly overrides?: NextjsRevalidationOverrides;
  /**
   * Override function properties.
   * @stability stable
   */
  readonly lambdaOptions?: aws_lambda.FunctionOptions;
  /**
   * @stability stable
   */
  readonly serverFunction?: NextjsServer;
  /**
   * @stability stable
   */
  readonly nextBuild?: NextjsBuild;
}
