// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { aws_cloudfront } from 'aws-cdk-lib';
import type { Construct } from 'constructs';
import type { NextjsInvalidationOverrides } from '..';

/**
 * OptionalNextjsInvalidationProps
 */
export interface OptionalNextjsInvalidationProps {
  /**
   * Overrides.
   * @stability stable
   */
  readonly overrides?: NextjsInvalidationOverrides;
  /**
   * CloudFront Distribution to invalidate.
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.IDistribution;
  /**
   * Constructs that should complete before invalidating CloudFront Distribution.
   * Useful for assets that must be deployed/updated before invalidating.
   * @stability stable
   */
  readonly dependencies?: Array<Construct>;
}
